#!/bin/bash

apt-get update
apt-get install -qqy git
publicdns=`curl http://169.254.169.254/latest/meta-data/public-hostname`
git clone https://github.com/jcooklin/OpenStackWorkshop.git
cd OpenStackWorkshop

#create user
memtotal=`grep MemTotal /proc/meminfo | awk '{print $2}'`
let mem_per_user=1024*768
let num_of_users=${memtotal}/${mem_per_user}
for i in `shuf -i 2000-65000 -n ${num_of_users}`
do
echo ""
echo "creating user$i..."
adduser --disabled-password --gecos "" user${i}
echo "setting standard passwd for user$i..."
echo "user${i}:password" | chpasswd
echo "setup home dir..."
echo ". /opt/stack/devstack/openrc" >> /home/user${i}/.bashrc
mkdir /home/user${i}/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKQlnp+lZmtcBLCIgyKaDfyUjQJNtjfoIIQec1nbsdlZ6ta9etrBsqHrbSb6/i9+rI5gINbK9F3eqxLrND/m5pFxDw1nsM7IGuZGUqoVZpYmqleTEm/GBQiXlP6thOew74tUePSKOjXtRPEzLh/m3Q341jMedwRt2XoZPyJiEJSmxqrk5OPinhMbHsxq6uukScpJ1xOSQDhqPp3Zl9EGb/lO5/+lpEO0oAt5IVnZfPI/ufxWsVojlgYq1ukZNSiMNTkI7+8aWA51H807/ywma3IgA7UB5cQsocR/z2kInF/J/u3LluAC/q5a2yqQV2Korz+rpPOMos0eJFAItTVt8t">> /home/user${i}/.ssh/authorized_keys
echo "StrictHostKeyChecking no" > /home/user${i}/.ssh/config
git archive master | tar -x -C /home/user${i}/
chown -R user${i}:user${i} /home/user${i}
chmod 640 /home/user${i}/.ssh/authorized_keys
echo "registering login..."
curl "http://ec2-23-20-190-233.compute-1.amazonaws.com/register/${publicdns}/user${i}/"
done

#enable password authentication and restart ssh
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
/etc/init.d/ssh restart
