#!/bin/bash

#create user
for i in `shuf -i 2000-65000 -n 10`
do
echo ""
echo "creating user$i..."
adduser --disabled-password --gecos "" user${i}
echo "setting standard passwd for user$i..."
echo "user${i}:password" | chpasswd
echo "setup home dir..."
echo ". /opt/stack/devstack/openrc" >> /home/user${i}/.bashrc
mkdir /home/user${i}/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKQlnp+lZmtcBLCIgyKaDfyUjQJNtjfoIIQec1nbsdlZ6ta9etrBsqHrbSb6/i9+rI5gINbK9F3eqxLrND/m5pFxDw1nsM7IGuZGUqoVZpYmqleTEm/GBQiXlP6thOew74tUePSKOjXtRPEzLh/m3Q341jMedwRt2XoZPyJiEJSmxqrk5OPinhMbHsxq6uukScpJ1xOSQDhqPp3Zl9EGb/lO5/+lpEO0oAt5IVnZfPI/ufxWsVojlgYq1ukZNSiMNTkI7+8aWA51H807/ywma3IgA7UB5cQsocR/z2kInF/J/u3LluAC/q5a2yqQV2Korz+rpPOMos0eJFAItTVt8t">> /home/user${i}/.ssh/authorized_keys
chown user${i}:user${i} /home/user${i}/.ssh/authorized_keys
chmod 640 /home/user${i}/.ssh/authorized_keys
echo "register account as available..."
echo "TODO"
done
