#!/bin/bash
URL='https://github.com/downloads/liftoff/GateOne/python-tornado_2.2-1_all.deb'; FILE=`mktemp`; wget "$URL" -qO $FILE && dpkg -i $FILE; rm $FILE
URL='https://github.com/downloads/liftoff/GateOne/gateone_1.0-2_all.deb'; FILE=`mktemp`; wget "$URL" -qO $FILE && dpkg -i $FILE; rm $FILE
/opt/gateone/gateone.py &
